/*
 * This file is generated by jOOQ.
 */
package org.yagi.motel.kernel.model.dsl;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.yagi.motel.kernel.model.dsl.tables.State;
import org.yagi.motel.kernel.model.dsl.tables.records.StateRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StateRecord> STATE__PK_STATE = Internal.createUniqueKey(State.STATE, DSL.name("pk_state"), new TableField[] { State.STATE.ID }, true);
}
