/*
 * This file is generated by jOOQ.
 */
package org.yagi.motel.kernel.model.dsl;


import org.yagi.motel.kernel.model.dsl.tables.State;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>state</code>.
     */
    public static final State STATE = State.STATE;
}
